name: Deployment

on:
  push:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Dev
        if: github.ref == 'refs/heads/dev'
        id: docker_build_dev
        uses: docker/build-push-action@v5
        with:
          context: ./bot
          file: ./bot/Dockerfile
          push: true
          tags: austin1237/lol-counter-bot:dev

      - name: Build and push Prod
        if: github.ref == 'refs/heads/main'
        id: docker_build_prod
        uses: docker/build-push-action@v5
        with:
          context: ./bot
          file: ./bot/Dockerfile
          push: true
          tags: austin1237/lol-counter-bot:latest
      
      - name: Set Docker image sha as env var Dev
        if: github.ref == 'refs/heads/dev'
        run: | 
          echo "TF_VAR_DOCKER_IMAGE_SHA=${{ steps.docker_build_dev.outputs.digest }}" >> $GITHUB_ENV
          echo ${{ steps.docker_build_dev.outputs.digest }}

      - name: Set Docker image sha as env var Prod
        if: github.ref == 'refs/heads/main'
        run: | 
          echo "TF_VAR_DOCKER_IMAGE_SHA=${{ steps.docker_build_prod.outputs.digest }}" >> $GITHUB_ENV
          echo ${{ steps.docker_build_prod.outputs.digest }}
      
      
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
        
      - name: Dev Deployment
        if: github.ref == 'refs/heads/dev'
        run: |
          cd terraform && terraform init
          terraform plan
          terraform apply -input=false -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
          TF_VAR_COUNTER_SOURCE_API_URL: ${{ secrets.COUNTER_SOURCE_API_URL }}
        
      - name: Prod Deployment
        if: github.ref == 'refs/heads/main'
        run: |
          cd terraform && terraform init
          (terraform workspace new prod || true) && terraform workspace select prod
          terraform plan
          terraform apply -input=false -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
          TF_VAR_COUNTER_SOURCE_API_URL: ${{ secrets.COUNTER_SOURCE_API_URL }}
      