name: Pull Request

on:
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Lint/Staticcheck
      uses: dominikh/staticcheck-action@v1.3.0
      with:
        version: "2023.1"
        install-go: false
        working-directory: bot

    - name: Build
      run: go build -v ./...
      working-directory: bot
      
    - name: Test
      run: go test -v ./...
      working-directory: bot
